# Generated by Django 4.1.2 on 2022-10-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
