# Generated by Django 4.1.2 on 2022-10-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
